<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2011-01-21 14:39

$extensionClassesPath = t3lib_extMgm::extPath('palm') . 'Classes/';
return array(
	'tx_extbase_reflection_objectaccess' => $extensionClassesPath . 'Reflection/ObjectAccess.php',
);
?>